# Generated by Django 3.1.7 on 2021-03-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_basket_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='cost',
        ),
    ]
