# Generated by Django 3.2 on 2021-04-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210411_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='activation_key_expiries',
            new_name='activation_key_expires',
        ),
    ]
